// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.machobv.models;

import nl.machobv.models.RouteIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RouteIntegrationTest_Roo_Configurable {
    
    declare @type: RouteIntegrationTest: @Configurable;
    
}
