// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.machobv.models;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.machobv.models.RouteWork;
import nl.machobv.models.RouteWorkDataOnDemand;
import nl.machobv.models.RouteWorkIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RouteWorkIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RouteWorkIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RouteWorkIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RouteWorkIntegrationTest: @Transactional;
    
    @Autowired
    RouteWorkDataOnDemand RouteWorkIntegrationTest.dod;
    
    @Test
    public void RouteWorkIntegrationTest.testCountRouteWorks() {
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", dod.getRandomRouteWork());
        long count = RouteWork.countRouteWorks();
        Assert.assertTrue("Counter for 'RouteWork' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RouteWorkIntegrationTest.testFindRouteWork() {
        RouteWork obj = dod.getRandomRouteWork();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to provide an identifier", id);
        obj = RouteWork.findRouteWork(id);
        Assert.assertNotNull("Find method for 'RouteWork' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RouteWork' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RouteWorkIntegrationTest.testFindAllRouteWorks() {
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", dod.getRandomRouteWork());
        long count = RouteWork.countRouteWorks();
        Assert.assertTrue("Too expensive to perform a find all test for 'RouteWork', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RouteWork> result = RouteWork.findAllRouteWorks();
        Assert.assertNotNull("Find all method for 'RouteWork' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RouteWork' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RouteWorkIntegrationTest.testFindRouteWorkEntries() {
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", dod.getRandomRouteWork());
        long count = RouteWork.countRouteWorks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RouteWork> result = RouteWork.findRouteWorkEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RouteWork' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RouteWork' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RouteWorkIntegrationTest.testFlush() {
        RouteWork obj = dod.getRandomRouteWork();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to provide an identifier", id);
        obj = RouteWork.findRouteWork(id);
        Assert.assertNotNull("Find method for 'RouteWork' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRouteWork(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RouteWork' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RouteWorkIntegrationTest.testMergeUpdate() {
        RouteWork obj = dod.getRandomRouteWork();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to provide an identifier", id);
        obj = RouteWork.findRouteWork(id);
        boolean modified =  dod.modifyRouteWork(obj);
        Integer currentVersion = obj.getVersion();
        RouteWork merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RouteWork' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RouteWorkIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", dod.getRandomRouteWork());
        RouteWork obj = dod.getNewTransientRouteWork(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RouteWork' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'RouteWork' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RouteWorkIntegrationTest.testRemove() {
        RouteWork obj = dod.getRandomRouteWork();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RouteWork' failed to provide an identifier", id);
        obj = RouteWork.findRouteWork(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RouteWork' with identifier '" + id + "'", RouteWork.findRouteWork(id));
    }
    
}
